---
# file: playbook_localhost.yml
#   Shortcut to run install tasks on the localhost without setting up an inventory.
#
# Run roles locally via following command:
#   ansible-playbook -i localhost, playbook_localhost.yml [-e var=val]* --tags=<tag[,tag]> --skip-tags=<tag[,tag]>

- hosts: localhost
  connection: local
  pre_tasks:
  - name: Create Galaxy user
    user:
      name: galaxy
      system: yes
      home: /galaxy

  roles:
  - galaxy

# Client dependencies need to be installed before running this, so uncomment
# once they are moved here
#   post_tasks:
#   - name: Run common startup to prefetch wheels
#     shell: "{{ galaxy_server_dir }}/scripts/common_startup.sh"
#     args:
#         chdir: "{{ galaxy_server_dir }}"

  # No need if using multi-stage build
  #  - name: Clean up
  #    apt:
  #      autoclean: yes
  #      autoremove: yes
