---
# file: playbook_localhost.yml
#   Shortcut to run install tasks on the localhost without setting up an inventory.
- hosts: localhost
  connection: local
  roles:
  - galaxy
  post_tasks:
    - name: Initialize welcome page
      template:
        src: files/welcome.html.j2
        dest: "{{ galaxy_server_dir }}/static/welcome.html"
