---
# file: playbook_localhost.yml
#   Shortcut to run install tasks on the localhost without setting up an inventory.
#
# Run roles locally via following command:
#   ansible-playbook -i localhost, playbook_localhost.yml [-e var=val]* --tags=<tag[,tag]> --skip-tags=<tag[,tag]>

- hosts: localhost
  connection: local
  pre_tasks:
    - name: Create Galaxy user
      user:
        name: galaxy
        system: yes
        home: /galaxy
  roles:
  - galaxy
  post_tasks:
    - name: Initialize welcome page
      template:
        src: files/welcome.html.j2
        dest: "{{ galaxy_server_dir }}/static/welcome.html"
