---
# file: playbook_localhost.yml
#   Shortcut to run install tasks on the localhost without setting up an inventory.
#
# Run roles locally via following command:
#   ansible-playbook -i localhost, playbook_localhost.yml [-e var=val]* --tags=<tag[,tag]> --skip-tags=<tag[,tag]>

- hosts: localhost
  connection: local

  roles:
  - galaxy-os

  post_tasks:
    - name: Clean up
      apt:
        autoclean: yes
        autoremove: yes
