kind: PersistentVolume
apiVersion: v1
metadata:
  name: galaxy-pv-volume
  labels:
    type: local
    app: galaxy
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # This is a host specific path where Galaxy files will be placed.
    path: "<change-this-to-path-to-directory>"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: galaxy-pv-claim
  labels:
    app: galaxy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
